keys:
  - &admin_sun 2C6A8AB960E26079CC987A0AEE55F605B6FAE752
  - &server_local age1rzssrxv8vrnud0q6amdte03slen9tkvdnaaayh5hwsvsqwuau5vspmv5n8
  - &server_hydra age1n72tu7kv98kcly6tty6ajnwwhg53xrafejw7mfmhjegqa3sssqkqrqe7ym
creation_rules:
  - key_groups:
      - pgp:
          - *admin_sun
        age:
          - *server_local
          - *server_hydra
