# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "tmpfs";
      fsType = "tmpfs";
      options = [ "defaults" "size=32G" "mode=755" ];
    };

  fileSystems."/persist" =
    {
      device = "/dev/disk/by-uuid/03d5b334-fa0d-4707-b250-4bebaf82ac1c";
      fsType = "btrfs";
      options = [ "subvol=persist" "noatime" "compress=zstd" "discard=async" "space_cache=v2" "autodefrag" ];
      neededForBoot = true;
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/03d5b334-fa0d-4707-b250-4bebaf82ac1c";
      fsType = "btrfs";
      options = [ "subvol=nix" "noatime" "compress=zstd" "discard=async" "space_cache=v2" "autodefrag" ];
    };

  fileSystems."/swap" =
    {
      device = "/dev/disk/by-uuid/03d5b334-fa0d-4707-b250-4bebaf82ac1c";
      fsType = "btrfs";
      options = [ "subvol=swap" "noatime" "nodatacow" "discard=async" "space_cache=v2" "autodefrag" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/7156-D56F";
      fsType = "vfat";
    };

  swapDevices =
    [
      { device = "/swap/swapfile"; size = 32 * 1024; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  hardware.enableAllFirmware = true;
  hardware.cpu.amd.updateMicrocode = true;
}
