# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  clash-dashboard = {
    pname = "clash-dashboard";
    version = "bf46fbd936eac84a6939360d5555e7bd1146bbbe";
    src = fetchgit {
      url = "https://github.com/Dreamacro/clash-dashboard.git";
      rev = "bf46fbd936eac84a6939360d5555e7bd1146bbbe";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-lJQXOPlMhHBWLMWtkyaEpMc+FaPvu/++I+CF2A6vSXA=";
    };
    date = "2023-01-20";
  };
  clash-premium-x86_64-linux = {
    pname = "clash-premium-x86_64-linux";
    version = "2023.01.29";
    src = fetchurl {
      url = "https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-amd64-2023.01.29.gz";
      sha256 = "sha256-LCN9HNBZZ1oAIeLxm/NnMdnD5Hrw1STgisXOUdSYPaY=";
    };
  };
  kmonad-bin = {
    pname = "kmonad-bin";
    version = "0.4.1";
    src = fetchurl {
      url = "https://github.com/kmonad/kmonad/releases/download/0.4.1/kmonad-0.4.1-linux";
      sha256 = "sha256-g55Y58wj1t0GhG80PAyb4PknaYGJ5JfaNe9RlnA/eo8=";
    };
  };
  maxmind-geoip = {
    pname = "maxmind-geoip";
    version = "20230112";
    src = fetchurl {
      url = "https://github.com/Dreamacro/maxmind-geoip/releases/download/20230112/Country.mmdb";
      sha256 = "sha256-mMu+U3gtoZmi6LrTMTqsNZKZ+w4J6LZ16Aorneyy7P8=";
    };
  };
  yacd = {
    pname = "yacd";
    version = "v0.3.8";
    src = fetchurl {
      url = "https://github.com/haishanh/yacd/releases/download/v0.3.8/yacd.tar.xz";
      sha256 = "sha256-1dfs3pGnCKeThhFnU+MqWfMsjLjuyA3tVsOrlOURulA=";
    };
  };
}
