# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  clash-dashboard = {
    pname = "clash-dashboard";
    version = "bf46fbd936eac84a6939360d5555e7bd1146bbbe";
    src = fetchgit {
      url = "https://github.com/Dreamacro/clash-dashboard.git";
      rev = "bf46fbd936eac84a6939360d5555e7bd1146bbbe";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-lJQXOPlMhHBWLMWtkyaEpMc+FaPvu/++I+CF2A6vSXA=";
    };
    date = "2023-01-20";
  };
  clash-premium-x86_64-linux = {
    pname = "clash-premium-x86_64-linux";
    version = "2023.02.16";
    src = fetchurl {
      url = "https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-amd64-2023.02.16.gz";
      sha256 = "sha256-dqGV4zRMlV9sTUqRawigLWu6toMRdeBn+McaUPZjAZ4=";
    };
  };
  kmonad-bin = {
    pname = "kmonad-bin";
    version = "0.4.1";
    src = fetchurl {
      url = "https://github.com/kmonad/kmonad/releases/download/0.4.1/kmonad-0.4.1-linux";
      sha256 = "sha256-g55Y58wj1t0GhG80PAyb4PknaYGJ5JfaNe9RlnA/eo8=";
    };
  };
  maxmind-geoip = {
    pname = "maxmind-geoip";
    version = "20230212";
    src = fetchurl {
      url = "https://github.com/Dreamacro/maxmind-geoip/releases/download/20230212/Country.mmdb";
      sha256 = "sha256-Tnma6tpET4Vrm5G8KmLpsVnpD2JIKts56kZQsBIbRZ8=";
    };
  };
  sweet = {
    pname = "sweet";
    version = "33ad60ca0db11808fdd576b5e13b05a82bafe9e2";
    src = fetchgit {
      url = "https://github.com/EliverLara/Sweet.git";
      rev = "33ad60ca0db11808fdd576b5e13b05a82bafe9e2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-NXfEBRgXOOQB+NyNI4LUrVXQRuhdbeAeU/JF1LsmcuI=";
    };
    date = "2023-02-12";
  };
  vscode-extension-github-copilot = {
    pname = "vscode-extension-github-copilot";
    version = "1.73.8685";
    src = fetchurl {
      url = "https://github.gallery.vsassets.io/_apis/public/gallery/publisher/github/extension/copilot/1.73.8685/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "copilot-1.73.8685.zip";
      sha256 = "sha256-W1j1VAuSM1sgxHRIahqVncUlknT+MPi7uutY+0NURZQ=";
    };
  };
  vscode-extension-ms-vscode-cpptools = {
    pname = "vscode-extension-ms-vscode-cpptools";
    version = "v1.14.3";
    src = fetchurl {
      url = "https://github.com/microsoft/vscode-cpptools/releases/download/v1.14.3/cpptools-linux.vsix";
      sha256 = "sha256-/Qw9HyiiqKhXlmSjPHcUdPNKwnSrt+sPTj5B9ctjVcc=";
    };
  };
  yacd = {
    pname = "yacd";
    version = "v0.3.8";
    src = fetchurl {
      url = "https://github.com/haishanh/yacd/releases/download/v0.3.8/yacd.tar.xz";
      sha256 = "sha256-1dfs3pGnCKeThhFnU+MqWfMsjLjuyA3tVsOrlOURulA=";
    };
  };
}
